### ISSUE TITLE
DocumentDirectoryPath changes after every testflight update

### ISSUE THREAD

**Issue by kyle-ssg** [itinance/react-native-fs#528] opened 2018-07-20 15:30 UTC
From what I can see, the DocumentDirectoryPath changes after every TestFlight update. This means that previously downloaded files cannot be accessed by using DocumentDirectoryPath in future builds.

Does this mean that I'd have to cache the first instance of DocumentDirectoryPath being used and always read/write from that?

Also, is this only the behaviour of TestFlight or updates in general?

**Comment by kyle-ssg** [comment] 2018-07-23 10:34
Update:
So to get around this currently I'll do the following:

```
AsyncStorage.getItem("folderPath", (err, res) => {
    if (!res) {
        AsyncStorage.setItem("folderPath", base_dir)
    } else if (res !== base_dir) {
        console.log("Moving", `${res}/documents`, `${base_dir}/documents`)
        FS.moveFile(`${res}/documents`, `${base_dir}/documents`)
            .then(() => {
                AsyncStorage.setItem("folderPath", base_dir);
            });
    }
});
```

**Comment by teknologist** [comment] 2018-08-26 15:31
Same issue here with apps distributed with Microsoft App Center...
Your workaround does the job! 

Thanks!

**Comment by kyle-ssg** [comment] 2018-08-27 14:59
Yeah, it's pretty crazy but I don't know whether this library could really avoid this issue - a new directory gets created per install

**Comment by fozzarelo** [comment] 2019-04-16 22:15
This looks more related to RN and testflight.
react-native-fs is affected, along with anything using the asyncStorage to store file paths and testflight.

@kyle-ssg Have you tested if this limited to testflight? or do apps updated through the appstore get hit ass well?

**Comment by rreiser-auti** [comment] 2019-05-22 14:25
I have the same issue, and it is happening with the app store app as well! Using RN 0.59.3

**Comment by fozzarelo** [comment] 2019-05-24 23:40
@rreiser-auti.
It's not a bug, it's a feature :-|.
Any new build you make will have a different path. You have to use dynamic paths.
With Expo I was able to compose my path using FileSystem.cacheDirectory + fileName. I am sure you will find a way using that's available to your environment.
I would close this issue btw.

**Closed** 2019-12-06 11:44 UTC
